- ros_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  ign_type_name: "ignition.msgs.Twist"

- ros_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  ign_type_name: "ignition.msgs.IMU"

- ros_topic_name: "lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  ign_type_name: "ignition.msgs.LaserScan"

- ros_topic_name: "lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  ign_type_name: "ignition.msgs.PointCloudPacked"
  
- ros_topic_name: "rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  ign_type_name: "ignition.msgs.CameraInfo"
  # TODO: odom, tf, rgbd cam x 5 
- ros_topic_name: "rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  ign_type_name: "ignition.msgs.Image"

- ros_topic_name: "rgbd_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  ign_type_name: "ignition.msgs.Image"

- ros_topic_name: "rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  ign_type_name: "ignition.msgs.PointCloudPacked"

# - ros_topic_name: "tf"
#   ign_topic_name: "model/rover/tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   ign_type_name: "ignition.msgs.Pose_V"

# - ros_topic_name: "wheel_odom"
#   ign_topic_name: "model/rover/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   ign_type_name: "ignition.msgs.Odometry"
